# See https://github.com/crate-ci/typos/blob/master/docs/reference.md to configure typos

[files]
extend-exclude = [
    "deps/",
    # crc16_slottable is primarily pre-generated random strings.
    "src/crc16_slottable.h",
]

[default.extend-words]
exat = "exat"
optin = "optin"
smove = "smove"

[type.c]
extend-ignore-re = [
    "BA3E2571", # sha1.c
    "D4C4DAA4", # sha1.c
    "Georg Nees",
    "\\[l\\]ist", # eval.c
]

[type.tcl]
extend-ignore-re = [
    "DUMPed",
]

[type.sv.extend-identifiers]
# sv = .h
module_gil_acquring = "module_gil_acquring"

[type.c.extend-identifiers]
clen = "clen"
fle = "fle"
module_gil_acquring = "module_gil_acquring"
nd = "nd"
ot = "ot"

[type.tcl.extend-identifiers]
fo = "fo"
oll = "oll"
stressers = "stressers"

[type.sv.extend-words]
# sv = .h
fo = "fo"
seeked = "seeked"

[type.c.extend-words]
fo = "fo"
limite = "limite"
seeked = "seeked"
tre = "tre"

[type.systemd.extend-words]
# systemd = .conf
ake = "ake"

[type.tcl.extend-words]
fo = "fo"
tre = "tre"
