name: Reply-schemas linter

on:
  push:
    paths:
      - 'src/commands/*.json'
  pull_request:
    paths:
      - 'src/commands/*.json'

concurrency:
  group: reply-schemas-linter-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  reply-schemas-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup nodejs
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
      - name: Install packages
        run: npm install ajv
      - name: linter
        run: node ./utils/reply_schema_linter.js

